ALTER TABLE vehicles ADD COLUMN length_mm TEXT;
ALTER TABLE vehicles ADD COLUMN weight_g TEXT;
ALTER TABLE vehicles ADD COLUMN color TEXT;
ALTER TABLE vehicles ADD COLUMN lettering TEXT;
ALTER TABLE vehicles ADD COLUMN load TEXT;
ALTER TABLE vehicles ADD COLUMN interior TEXT;
ALTER TABLE vehicles ADD COLUMN axles TEXT;
ALTER TABLE vehicles ADD COLUMN axle_count TEXT;
ALTER TABLE vehicles ADD COLUMN traction_tire_count TEXT;
ALTER TABLE vehicles ADD COLUMN wheelset TEXT;
ALTER TABLE vehicles ADD COLUMN coupling_same INTEGER NOT NULL DEFAULT 0;
ALTER TABLE vehicles ADD COLUMN coupling_front TEXT;
ALTER TABLE vehicles ADD COLUMN coupling_rear TEXT;
ALTER TABLE vehicles ADD COLUMN power_pickup TEXT;
ALTER TABLE vehicles ADD COLUMN adapter TEXT;
ALTER TABLE vehicles ADD COLUMN drive_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE vehicles ADD COLUMN drive_description TEXT;
ALTER TABLE vehicles ADD COLUMN headlights_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE vehicles ADD COLUMN headlights_description TEXT;
ALTER TABLE vehicles ADD COLUMN lighting_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE vehicles ADD COLUMN lighting_description TEXT;
ALTER TABLE vehicles ADD COLUMN sound_generator_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE vehicles ADD COLUMN sound_generator_description TEXT;
ALTER TABLE vehicles ADD COLUMN smoke_generator_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE vehicles ADD COLUMN smoke_generator_description TEXT;
ALTER TABLE vehicles ADD COLUMN additional_info TEXT;
ALTER TABLE vehicles ADD COLUMN qr_code_enabled INTEGER NOT NULL DEFAULT 0;
